[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Sutax <root@stxtamfan>"]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "jax>=0.5.0",
    "matplotlib>=3.10.0",
    "numpy>=2.2.3",
    "pandas>=2.2.3",
    "requests==2.32.3",
]
