name: Bot

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  run-bot:
    timeout-minutes: 61
    runs-on: ubuntu-latest
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      GH_REPO: ${{ github.repository }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip3 install requests flask
        sudo chmod +x *
       

    - name: Run Bot
      run: |
        export GH_PAT="${GH_PAT}"
        export GH_REPO="${GH_REPO}"
        sudo bash x.sh
